    fn setup_identity_always_items() {
        setup_test_tables();
        Spi::run(
            "CREATE TABLE IF NOT EXISTS test_identity_always_items (
                 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                 owner_id TEXT NOT NULL DEFAULT current_setting('synchro.user_id', true),
                 value TEXT NOT NULL,
                 seq BIGINT GENERATED ALWAYS AS IDENTITY,
                 client_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
                 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                 deleted_at TIMESTAMPTZ
             );
             SELECT synchro.synchro_prepare_projection_view(
                 'public.test_identity_always_items',
                 'test_identity_always_items',
                 ARRAY['owner_id']
             );
             SELECT tests.register_test_table(
                 'test_identity_always_items',
                 $$SELECT 'user:' || (owner_id #>> '{}')
                   FROM synchro_projection.test_identity_always_items
                  WHERE record_id = p_key::text$$,
                 'single_scope',
                 'id', 'updated_at', 'deleted_at', 'enabled'
             )",
        )
        .expect("create identity test table");
        activate_pending_registry_for_test();
    }

    fn identity_always_state_counts(record_id: &str) -> (i64, i64, i64) {
        let (source_rows, fences, versions) = Spi::get_three_with_args::<i64, i64, i64>(
            "SELECT (
                 SELECT count(*)
                 FROM public.test_identity_always_items
                 WHERE id = $1::uuid
             ), (
                 SELECT count(*)
                 FROM synchro.sync_write_fences fence
                 JOIN synchro.sync_registry registry
                   ON registry.relation_id = fence.relation_id
                 JOIN synchro.sync_registry_generations generation
                   ON generation.generation = registry.registry_generation
                 WHERE generation.state = 'active'
                   AND registry.table_name = 'test_identity_always_items'
                   AND $1 IN (fence.old_record_id, fence.new_record_id)
             ), (
                 SELECT count(*)
                 FROM synchro.sync_row_versions version
                 JOIN synchro.sync_registry registry
                   ON registry.relation_id = version.relation_id
                 JOIN synchro.sync_registry_generations generation
                   ON generation.generation = registry.registry_generation
                 WHERE generation.state = 'active'
                   AND registry.table_name = 'test_identity_always_items'
                   AND version.record_id = $1
             )",
            &[record_id.into()],
        )
        .expect("read identity write state");
        (
            source_rows.expect("identity source count"),
            fences.expect("identity fence count"),
            versions.expect("identity row-version count"),
        )
    }

    #[pg_test]
    fn identity_always_field_is_not_writable() {
        setup_identity_always_items();
        let fields: pgrx::JsonB = Spi::get_one(
            "SELECT jsonb_object_agg(field.physical_column::text, field.writable)
             FROM synchro.sync_registry registry
             JOIN synchro.sync_registry_fields field
               ON field.registry_generation = registry.registry_generation
              AND field.relation_id = registry.relation_id
             JOIN synchro.sync_registry_generations generation
               ON generation.generation = registry.registry_generation
             WHERE generation.state = 'active'
               AND registry.table_name = 'test_identity_always_items'",
        )
        .expect("read identity field writability")
        .expect("identity field writability");

        assert_eq!(fields.0["seq"], json!(false));
        assert_eq!(fields.0["client_seq"], json!(true));
    }

    #[pg_test]
    fn push_naming_identity_always_field_rejects_terminal() {
        setup_identity_always_items();
        let user_id = "identity-user";
        let client_id = "identity-client";
        let rejected_record_id = "92000000-0000-4000-8000-000000000001";
        let updated_record_id = "92000000-0000-4000-8000-000000000002";
        register_client(user_id, client_id);

        let rejected_insert = push_client(
            user_id,
            client_id,
            "identity-rejected-insert",
            vec![push_mutation(
                (user_id, client_id),
                "identity-rejected-insert",
                "test_identity_always_items",
                "insert",
                rejected_record_id,
                None,
                Some(&[("value", json!("named")), ("seq", json!("7"))]),
            )],
        );
        assert_eq!(
            rejected_insert.json["rejected"][0]["status"],
            "rejected_terminal"
        );
        assert_eq!(
            rejected_insert.json["rejected"][0]["code"],
            "validation_failed"
        );
        assert_eq!(identity_always_state_counts(rejected_record_id), (0, 0, 0));

        let inserted = push_client(
            user_id,
            client_id,
            "identity-update-insert",
            vec![push_mutation(
                (user_id, client_id),
                "identity-update-insert",
                "test_identity_always_items",
                "insert",
                updated_record_id,
                None,
                Some(&[("value", json!("original"))]),
            )],
        );
        let inserted_outcome = &inserted.json["accepted"][0];
        assert_eq!(inserted_outcome["status"], "applied");
        let before_update = identity_always_state_counts(updated_record_id);
        let source_before: pgrx::JsonB = Spi::get_one_with_args(
            "SELECT jsonb_build_object('value', value, 'seq', seq::text)
             FROM public.test_identity_always_items
             WHERE id = $1::uuid",
            &[updated_record_id.into()],
        )
        .expect("read identity source row")
        .expect("identity source row");

        let rejected_update = push_client(
            user_id,
            client_id,
            "identity-rejected-update",
            vec![push_mutation(
                (user_id, client_id),
                "identity-rejected-update",
                "test_identity_always_items",
                "update",
                updated_record_id,
                inserted_outcome["server_version"].as_str(),
                Some(&[("seq", json!("8"))]),
            )],
        );
        assert_eq!(
            rejected_update.json["rejected"][0]["status"],
            "rejected_terminal"
        );
        assert_eq!(
            rejected_update.json["rejected"][0]["code"],
            "validation_failed"
        );
        let source_after: pgrx::JsonB = Spi::get_one_with_args(
            "SELECT jsonb_build_object('value', value, 'seq', seq::text)
             FROM public.test_identity_always_items
             WHERE id = $1::uuid",
            &[updated_record_id.into()],
        )
        .expect("read identity source row after update")
        .expect("identity source row after update");
        assert_eq!(source_after.0, source_before.0);
        assert_eq!(identity_always_state_counts(updated_record_id), before_update);
    }

    #[pg_test]
    fn push_insert_omitting_identity_always_field_applies() {
        setup_identity_always_items();
        let user_id = "identity-omit-user";
        let client_id = "identity-omit-client";
        let record_id = "92000000-0000-4000-8000-000000000003";
        register_client(user_id, client_id);

        let response = push_client(
            user_id,
            client_id,
            "identity-omit-insert",
            vec![push_mutation(
                (user_id, client_id),
                "identity-omit-insert",
                "test_identity_always_items",
                "insert",
                record_id,
                None,
                Some(&[("value", json!("generated"))]),
            )],
        );

        let outcome = &response.json["accepted"][0];
        assert_eq!(outcome["status"], "applied");
        assert_row_outcome_matches_source(outcome, "test_identity_always_items", record_id);
        let source_seq: String = Spi::get_one_with_args(
            "SELECT seq::text
             FROM public.test_identity_always_items
             WHERE id = $1::uuid",
            &[record_id.into()],
        )
        .expect("read generated identity value")
        .expect("generated identity value");
        assert_eq!(
            outcome["server_row"][field_id("test_identity_always_items", "seq")].as_str(),
            Some(source_seq.as_str())
        );
    }

    #[pg_test]
    fn push_insert_with_by_default_identity_value_applies() {
        setup_identity_always_items();
        let user_id = "identity-default-user";
        let client_id = "identity-default-client";
        let record_id = "92000000-0000-4000-8000-000000000004";
        register_client(user_id, client_id);

        let response = push_client(
            user_id,
            client_id,
            "identity-default-insert",
            vec![push_mutation(
                (user_id, client_id),
                "identity-default-insert",
                "test_identity_always_items",
                "insert",
                record_id,
                None,
                Some(&[("value", json!("client value")), ("client_seq", json!("77"))]),
            )],
        );

        let outcome = &response.json["accepted"][0];
        assert_eq!(outcome["status"], "applied");
        assert_row_outcome_matches_source(outcome, "test_identity_always_items", record_id);
        assert_eq!(
            outcome["server_row"][field_id("test_identity_always_items", "client_seq")],
            json!("77")
        );
        assert_eq!(
            Spi::get_one_with_args::<i64>(
                "SELECT client_seq
                 FROM public.test_identity_always_items
                 WHERE id = $1::uuid",
                &[record_id.into()],
            )
            .expect("read BY DEFAULT identity value"),
            Some(77)
        );
    }

    fn setup_database_generated_key_tables() {
        setup_test_tables();
        set_test_publication_generated_columns("stored");
        Spi::run(
            "CREATE TABLE IF NOT EXISTS test_identity_always_key_items (
                 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                 value TEXT NOT NULL,
                 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                 deleted_at TIMESTAMPTZ
             );
             CREATE TABLE IF NOT EXISTS test_generated_key_items (
                 source_id BIGINT NOT NULL,
                 id BIGINT GENERATED ALWAYS AS (source_id) STORED PRIMARY KEY,
                 value TEXT NOT NULL,
                 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                 deleted_at TIMESTAMPTZ
             )",
        )
        .expect("create database-generated key tables");
    }

    fn database_generated_key_registry_count(table_name: &str) -> i64 {
        Spi::get_one_with_args::<i64>(
            "SELECT count(*)
             FROM synchro.sync_registry
             WHERE registry_generation = (
                     SELECT max(generation) FROM synchro.sync_registry_generations
                 )
               AND physical_relation_oid = $1::pg_catalog.regclass",
            &[table_name.into()],
        )
        .expect("read database-generated key registry count")
        .expect("database-generated key registry count")
    }

    #[pg_test]
    fn push_enabled_registration_rejects_database_generated_key() {
        setup_database_generated_key_tables();

        expect_registration_rejected(
            "tests.register_test_table(
                 'test_identity_always_key_items',
                 $$SELECT 'global'::text$$,
                 'single_scope',
                 'id', 'updated_at', 'deleted_at', 'enabled'
             )",
        );
        expect_registration_rejected(
            "tests.register_test_table(
                 'test_generated_key_items',
                 $$SELECT 'global'::text$$,
                 'single_scope',
                 'id', 'updated_at', 'deleted_at', 'enabled'
             )",
        );

        assert_eq!(
            database_generated_key_registry_count("public.test_identity_always_key_items"),
            0
        );
        assert_eq!(
            database_generated_key_registry_count("public.test_generated_key_items"),
            0
        );
    }

    #[pg_test]
    fn read_only_registration_accepts_database_generated_key() {
        setup_database_generated_key_tables();

        Spi::run(
            "SELECT tests.register_test_table(
                 'test_identity_always_key_items',
                 $$SELECT 'global'::text$$,
                 'single_scope',
                 'id', 'updated_at', 'deleted_at', 'read_only'
             );
             SELECT tests.register_test_table(
                 'test_generated_key_items',
                 $$SELECT 'global'::text$$,
                 'single_scope',
                 'id', 'updated_at', 'deleted_at', 'read_only'
             )",
        )
        .expect("register read-only database-generated keys");

        assert_eq!(
            database_generated_key_registry_count("public.test_identity_always_key_items"),
            1
        );
        assert_eq!(
            database_generated_key_registry_count("public.test_generated_key_items"),
            1
        );
    }

    fn setup_identity_drift_items() {
        setup_test_tables();
        Spi::run(
            "CREATE TABLE IF NOT EXISTS test_identity_drift_items (
                 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                 value TEXT NOT NULL,
                 client_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
                 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                 deleted_at TIMESTAMPTZ
             );
             SELECT tests.register_test_table(
                 'test_identity_drift_items',
                 $$SELECT 'global'::text$$,
                 'single_scope',
                 'id', 'updated_at', 'deleted_at', 'enabled'
             )",
        )
        .expect("create identity drift table");
        activate_pending_registry_for_test();
    }

    fn alter_identity_drift_field_to_always() {
        Spi::run(
            "ALTER TABLE public.test_identity_drift_items
             ALTER COLUMN client_seq SET GENERATED ALWAYS",
        )
        .expect("change identity field to ALWAYS");
    }

    fn identity_drift_registration_error() -> Option<String> {
        Spi::run(
            "CREATE TABLE IF NOT EXISTS test_identity_drift_trigger (
                 id UUID PRIMARY KEY,
                 value TEXT NOT NULL,
                 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                 deleted_at TIMESTAMPTZ
             );
             CREATE TEMP TABLE identity_drift_registration_result (message TEXT)",
        )
        .expect("create identity drift registration fixture");
        Spi::run(
            "DO $test$
             BEGIN
                 BEGIN
                     PERFORM tests.register_test_table(
                         'test_identity_drift_trigger',
                         $$SELECT 'global'::text$$,
                         'single_scope',
                         'id', 'updated_at', 'deleted_at', 'enabled'
                     );
                     INSERT INTO identity_drift_registration_result VALUES (NULL);
                 EXCEPTION WHEN OTHERS THEN
                     INSERT INTO identity_drift_registration_result VALUES (SQLERRM);
                 END;
             END
             $test$",
        )
        .expect("run identity drift registration");
        Spi::get_one::<String>("SELECT message FROM identity_drift_registration_result")
            .expect("read identity drift registration result")
    }

    #[pg_test]
    fn registry_validation_reports_identity_drift() {
        setup_identity_drift_items();
        alter_identity_drift_field_to_always();

        assert_eq!(
            identity_drift_registration_error().as_deref(),
            Some("registered field metadata has drifted")
        );
    }

    #[pg_test]
    fn readiness_relation_identity_fails_for_database_generated_drift() {
        setup_identity_drift_items();
        alter_identity_drift_field_to_always();

        let detail: pgrx::JsonB = Spi::get_one("SELECT synchro.synchro_health_detail()")
            .expect("read identity drift health detail")
            .expect("identity drift health detail");
        assert_ne!(
            detail.0["checks"]["relation_identity"]["state"].as_str(),
            Some("ok")
        );
    }
