    fn setup_source_filled_items() {
        setup_test_tables();
        Spi::run(
            "CREATE TABLE IF NOT EXISTS test_source_filled_items (
                 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                 owner_id TEXT NOT NULL DEFAULT current_setting('synchro.user_id', true),
                 value TEXT NOT NULL,
                 slug TEXT NOT NULL,
                 seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
                 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                 deleted_at TIMESTAMPTZ
             );
             CREATE OR REPLACE FUNCTION public.test_source_filled_items_slug()
             RETURNS trigger LANGUAGE plpgsql AS $$
             BEGIN
                 NEW.slug := COALESCE(lower(NEW.value), 'missing') || '-slug';
                 RETURN NEW;
             END
             $$;
             DROP TRIGGER IF EXISTS test_source_filled_items_slug ON public.test_source_filled_items;
             CREATE TRIGGER test_source_filled_items_slug
             BEFORE INSERT ON public.test_source_filled_items
             FOR EACH ROW EXECUTE FUNCTION public.test_source_filled_items_slug();
             SELECT synchro.synchro_prepare_projection_view(
                 'public.test_source_filled_items',
                 'test_source_filled_items',
                 ARRAY['owner_id']
             );
             SELECT tests.register_test_table(
                 'test_source_filled_items',
                 $$SELECT 'user:' || (owner_id #>> '{}')
                   FROM synchro_projection.test_source_filled_items
                  WHERE record_id = p_key::text$$,
                 'single_scope',
                 'id', 'updated_at', 'deleted_at', 'enabled',
                 ARRAY['slug']
             )",
        )
        .expect("create and register source-filled test table");
        activate_pending_registry_for_test();
    }

    fn setup_same_row_trigger_items() {
        setup_test_tables();
        Spi::run(
            "CREATE TABLE IF NOT EXISTS test_same_row_trigger_items (
                 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                 owner_id TEXT NOT NULL DEFAULT current_setting('synchro.user_id', true),
                 value TEXT NOT NULL,
                 trigger_value TEXT NOT NULL DEFAULT '',
                 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                 deleted_at TIMESTAMPTZ
             );
             CREATE OR REPLACE FUNCTION public.zz_test_same_row_trigger_items()
             RETURNS trigger LANGUAGE plpgsql AS $$
             BEGIN
                 IF pg_trigger_depth() = 1 THEN
                     UPDATE public.test_same_row_trigger_items
                     SET trigger_value = NEW.value || '-triggered'
                     WHERE id = NEW.id;
                 END IF;
                 RETURN NULL;
             END
             $$;
             DROP TRIGGER IF EXISTS zz_test_same_row_trigger_items
                 ON public.test_same_row_trigger_items;
             CREATE TRIGGER zz_test_same_row_trigger_items
             AFTER INSERT OR UPDATE ON public.test_same_row_trigger_items
             FOR EACH ROW EXECUTE FUNCTION public.zz_test_same_row_trigger_items();
             SELECT synchro.synchro_prepare_projection_view(
                 'public.test_same_row_trigger_items',
                 'test_same_row_trigger_items',
                 ARRAY['owner_id']
             );
             SELECT tests.register_test_table(
                 'test_same_row_trigger_items',
                 $$SELECT 'user:' || (owner_id #>> '{}')
                   FROM synchro_projection.test_same_row_trigger_items
                  WHERE record_id = p_key::text$$,
                 'single_scope',
                 'id', 'updated_at', 'deleted_at', 'enabled'
             )",
        )
        .expect("create and register same-row trigger test table");
        activate_pending_registry_for_test();
    }

    fn setup_peer_trigger_items() {
        setup_test_tables();
        Spi::run(
            "CREATE TABLE IF NOT EXISTS test_peer_trigger_items (
                 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                 owner_id TEXT NOT NULL DEFAULT current_setting('synchro.user_id', true),
                 value TEXT NOT NULL,
                 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                 deleted_at TIMESTAMPTZ
             );
             CREATE OR REPLACE FUNCTION public.zz_test_peer_trigger_items()
             RETURNS trigger LANGUAGE plpgsql AS $$
             BEGIN
                 IF NEW.id <> '95000000-0000-4000-8000-000000000002'::uuid THEN
                     INSERT INTO public.test_peer_trigger_items (id, value)
                     VALUES ('95000000-0000-4000-8000-000000000002', 'peer')
                     ON CONFLICT (id) DO UPDATE SET value = EXCLUDED.value;
                 END IF;
                 RETURN NULL;
             END
             $$;
             DROP TRIGGER IF EXISTS zz_test_peer_trigger_items
                 ON public.test_peer_trigger_items;
             CREATE TRIGGER zz_test_peer_trigger_items
             AFTER INSERT ON public.test_peer_trigger_items
             FOR EACH ROW EXECUTE FUNCTION public.zz_test_peer_trigger_items();
             SELECT synchro.synchro_prepare_projection_view(
                 'public.test_peer_trigger_items',
                 'test_peer_trigger_items',
                 ARRAY['owner_id']
             );
             SELECT tests.register_test_table(
                 'test_peer_trigger_items',
                 $$SELECT 'user:' || (owner_id #>> '{}')
                   FROM synchro_projection.test_peer_trigger_items
                  WHERE record_id = p_key::text$$,
                 'single_scope',
                 'id', 'updated_at', 'deleted_at', 'enabled'
             )",
        )
        .expect("create and register peer trigger test table");
        activate_pending_registry_for_test();
    }

    fn source_filled_next_sequence_value() -> i64 {
        Spi::get_one(
            "SELECT nextval(pg_get_serial_sequence('public.test_source_filled_items', 'seq'))",
        )
        .expect("read source-filled sequence")
        .expect("source-filled sequence value")
    }

    fn source_filled_state_counts(record_id: &str) -> (i64, i64, i64) {
        let (source_rows, fences, versions) = Spi::get_three_with_args::<i64, i64, i64>(
            "SELECT (
                 SELECT count(*)
                 FROM public.test_source_filled_items
                 WHERE id = $1::uuid
             ), (
                 SELECT count(*)
                 FROM synchro.sync_write_fences fence
                 JOIN synchro.sync_registry registry
                   ON registry.relation_id = fence.relation_id
                 JOIN synchro.sync_registry_generations generation
                   ON generation.generation = registry.registry_generation
                 WHERE generation.state = 'active'
                   AND registry.table_name = 'test_source_filled_items'
                   AND $1 IN (fence.old_record_id, fence.new_record_id)
             ), (
                 SELECT count(*)
                 FROM synchro.sync_row_versions version
                 JOIN synchro.sync_registry registry
                   ON registry.relation_id = version.relation_id
                 JOIN synchro.sync_registry_generations generation
                   ON generation.generation = registry.registry_generation
                 WHERE generation.state = 'active'
                   AND registry.table_name = 'test_source_filled_items'
                   AND version.record_id = $1
             )",
            &[record_id.into()],
        )
        .expect("read source-filled rejected write state");
        (
            source_rows.expect("source-filled source count"),
            fences.expect("source-filled fence count"),
            versions.expect("source-filled row-version count"),
        )
    }

    fn assert_last_fence_matches_outcome(
        table_name: &str,
        record_id: &str,
        mutation_id: &str,
        outcome: &Value,
    ) {
        let state: pgrx::JsonB = Spi::get_one_with_args(
            "SELECT jsonb_build_object(
                 'count', count(*),
                 'last_version',
                 (array_agg(row_version::text ORDER BY dml_ordinal DESC))[1]
             )
             FROM synchro.sync_write_fences fence
             JOIN synchro.sync_registry registry
               ON registry.relation_id = fence.relation_id
             JOIN synchro.sync_registry_generations generation
               ON generation.generation = registry.registry_generation
             WHERE generation.state = 'active'
               AND registry.table_name = $1
               AND fence.mutation_id = $2
               AND $3 IN (fence.old_record_id, fence.new_record_id)",
            &[table_name.into(), mutation_id.into(), record_id.into()],
        )
        .expect("read source-write fences")
        .expect("source-write fence state");
        let count = state.0["count"].as_i64().expect("source-write fence count");
        let last_version = state.0["last_version"]
            .as_str()
            .expect("source-write last fence version");
        assert!(count > 1);
        assert_eq!(outcome["server_version"].as_str(), Some(last_version));
        assert_eq!(current_row_version(table_name, record_id), last_version);
    }

    fn source_write_mutation(
        user_id: &str,
        client_id: &str,
        mutation_label: &str,
        table_name: &str,
        operation: &str,
        record_id: &str,
    ) -> synchro_core::contract::Mutation {
        serde_json::from_value(push_mutation(
            (user_id, client_id),
            mutation_label,
            table_name,
            operation,
            record_id,
            None,
            None,
        ))
        .expect("build source-write mutation")
    }

    fn current_fence_version(
        table_name: &str,
        record_id: &str,
        mutation: &synchro_core::contract::Mutation,
    ) -> Option<crate::push::UnitEndFence> {
        Spi::connect(|client| {
            let registration = crate::registry::load_registry_from_client(client)?
                .into_iter()
                .find(|registration| registration.table_name == table_name)
                .expect("source-write table registration");
            Ok::<_, pgrx::spi::Error>(crate::push::load_current_fence_version(
                client,
                mutation,
                &registration,
                record_id,
            ))
        })
        .expect("read source-write fence version")
    }

    fn set_source_write_mutation(mutation_id: &str) {
        Spi::run_with_args(
            "SELECT set_config('synchro.mutation_id', $1, true)",
            &[mutation_id.into()],
        )
        .expect("set source-write mutation identity");
    }

    #[pg_test]
    fn push_insert_uses_source_filled_defaults_and_identity() {
        setup_source_filled_items();
        let user_id = "source-filled-user";
        let client_id = "source-filled-client";
        let record_id = "91000000-0000-4000-8000-000000000001";
        register_client(user_id, client_id);

        let response = push_client(
            user_id,
            client_id,
            "source-filled-insert",
            vec![push_mutation(
                (user_id, client_id),
                "source-filled-insert",
                "test_source_filled_items",
                "insert",
                record_id,
                None,
                Some(&[("value", json!("filled"))]),
            )],
        );

        let outcome = &response.json["accepted"][0];
        assert_eq!(outcome["status"], "applied");
        assert_row_outcome_matches_source(outcome, "test_source_filled_items", record_id);
        assert_eq!(
            outcome["server_row"][field_id("test_source_filled_items", "value")],
            json!("filled")
        );
        assert_eq!(
            outcome["server_row"][field_id("test_source_filled_items", "seq")],
            json!("1")
        );
        assert_matching_fence(
            &mutation_id(user_id, client_id, "source-filled-insert"),
            outcome["server_version"]
                .as_str()
                .expect("source-filled server version"),
        );
    }

    #[pg_test]
    fn push_insert_missing_required_value_rejects_terminal_and_replays() {
        setup_source_filled_items();
        let user_id = "source-filled-user";
        let client_id = "source-filled-client";
        let record_id = "91000000-0000-4000-8000-000000000002";
        register_client(user_id, client_id);
        let request = push_request(
            user_id,
            client_id,
            "source-filled-missing-value",
            vec![push_mutation(
                (user_id, client_id),
                "source-filled-missing-value",
                "test_source_filled_items",
                "insert",
                record_id,
                None,
                Some(&[("owner_id", json!(user_id))]),
            )],
        );
        let prior_sequence_value = source_filled_next_sequence_value();

        let first = execute_push(user_id, &request);

        assert_eq!(first.json["rejected"][0]["status"], "rejected_terminal");
        assert_eq!(
            first.json["rejected"][0]["code"].as_str(),
            Some("validation_failed")
        );
        assert_eq!(source_filled_state_counts(record_id), (0, 0, 0));
        assert_eq!(
            source_filled_next_sequence_value(),
            prior_sequence_value + 2,
            "the physical insert must evaluate the identity default before it fails"
        );

        let replay = execute_push(user_id, &request);
        assert_eq!(replay.raw, first.raw);
    }

    #[pg_test]
    fn push_insert_rejects_non_writable_column() {
        setup_source_filled_items();
        let user_id = "source-filled-user";
        let client_id = "source-filled-client";
        register_client(user_id, client_id);

        let response = push_client(
            user_id,
            client_id,
            "source-filled-read-only",
            vec![push_mutation(
                (user_id, client_id),
                "source-filled-read-only",
                "test_source_filled_items",
                "insert",
                "91000000-0000-4000-8000-000000000003",
                None,
                Some(&[
                    ("value", json!("invalid")),
                    ("updated_at", json!("2026-09-27T00:00:00.000000Z")),
                ]),
            )],
        );

        assert_eq!(response.json["rejected"][0]["status"], "rejected_terminal");
        assert_eq!(
            response.json["rejected"][0]["code"].as_str(),
            Some("validation_failed")
        );
    }

    #[pg_test]
    fn push_uses_last_same_row_fence_after_trigger_writes() {
        setup_same_row_trigger_items();
        let user_id = "same-row-user";
        let client_id = "same-row-client";
        let record_id = "92000000-0000-4000-8000-000000000001";
        register_client(user_id, client_id);

        let insert_label = "same-row-insert";
        let insert = push_client(
            user_id,
            client_id,
            insert_label,
            vec![push_mutation(
                (user_id, client_id),
                insert_label,
                "test_same_row_trigger_items",
                "insert",
                record_id,
                None,
                Some(&[("value", json!("first"))]),
            )],
        );
        let insert_outcome = &insert.json["accepted"][0];
        assert_eq!(insert_outcome["status"], "applied");
        assert_row_outcome_matches_source(insert_outcome, "test_same_row_trigger_items", record_id);
        assert_eq!(
            insert_outcome["server_row"][field_id("test_same_row_trigger_items", "trigger_value")],
            json!("first-triggered")
        );
        assert_last_fence_matches_outcome(
            "test_same_row_trigger_items",
            record_id,
            &mutation_id(user_id, client_id, insert_label),
            insert_outcome,
        );

        let update_label = "same-row-update";
        let update = push_client(
            user_id,
            client_id,
            update_label,
            vec![push_mutation(
                (user_id, client_id),
                update_label,
                "test_same_row_trigger_items",
                "update",
                record_id,
                insert_outcome["server_version"].as_str(),
                Some(&[("value", json!("second"))]),
            )],
        );
        let update_outcome = &update.json["accepted"][0];
        assert_eq!(update_outcome["status"], "applied");
        assert_row_outcome_matches_source(update_outcome, "test_same_row_trigger_items", record_id);
        assert_eq!(
            update_outcome["server_row"][field_id("test_same_row_trigger_items", "trigger_value")],
            json!("second-triggered")
        );
        assert_last_fence_matches_outcome(
            "test_same_row_trigger_items",
            record_id,
            &mutation_id(user_id, client_id, update_label),
            update_outcome,
        );

        let delete_label = "same-row-delete";
        let delete = push_client(
            user_id,
            client_id,
            delete_label,
            vec![push_mutation(
                (user_id, client_id),
                delete_label,
                "test_same_row_trigger_items",
                "delete",
                record_id,
                update_outcome["server_version"].as_str(),
                None,
            )],
        );
        let delete_outcome = &delete.json["accepted"][0];
        assert_eq!(delete_outcome["status"], "applied");
        assert_row_outcome_matches_source(delete_outcome, "test_same_row_trigger_items", record_id);
        assert_last_fence_matches_outcome(
            "test_same_row_trigger_items",
            record_id,
            &mutation_id(user_id, client_id, delete_label),
            delete_outcome,
        );
    }

    #[pg_test]
    fn push_uses_pushed_row_fence_when_trigger_writes_peer() {
        setup_peer_trigger_items();
        let user_id = "peer-row-user";
        let client_id = "peer-row-client";
        let record_id = "95000000-0000-4000-8000-000000000001";
        let peer_id = "95000000-0000-4000-8000-000000000002";
        let mutation_label = "peer-row-insert";
        register_client(user_id, client_id);

        let response = push_client(
            user_id,
            client_id,
            mutation_label,
            vec![push_mutation(
                (user_id, client_id),
                mutation_label,
                "test_peer_trigger_items",
                "insert",
                record_id,
                None,
                Some(&[("value", json!("pushed"))]),
            )],
        );

        let outcome = &response.json["accepted"][0];
        assert_eq!(outcome["status"], "applied");
        assert_row_outcome_matches_source(outcome, "test_peer_trigger_items", record_id);
        let mutation_id = mutation_id(user_id, client_id, mutation_label);
        let versions: pgrx::JsonB = Spi::get_one_with_args(
            "SELECT jsonb_object_agg(record_id, row_version::text)
             FROM (
                 SELECT COALESCE(new_record_id, old_record_id) AS record_id, row_version
                 FROM synchro.sync_write_fences
                 WHERE mutation_id = $1
                   AND COALESCE(new_record_id, old_record_id) IN ($2, $3)
             ) fences",
            &[mutation_id.into(), record_id.into(), peer_id.into()],
        )
        .expect("read pushed and peer fence versions")
        .expect("pushed and peer fence versions");
        let pushed_version = versions.0[record_id]
            .as_str()
            .expect("pushed-row fence version");
        let peer_version = versions.0[peer_id].as_str().expect("peer-row fence version");
        assert_eq!(outcome["server_version"].as_str(), Some(pushed_version));
        assert_ne!(pushed_version, peer_version);
        assert_eq!(current_row_version("test_peer_trigger_items", record_id), pushed_version);
        assert_eq!(current_row_version("test_peer_trigger_items", peer_id), peer_version);
    }

    #[pg_test]
    fn push_fence_lookup_fails_closed_without_fence() {
        setup_same_row_trigger_items();
        let mutation = source_write_mutation(
            "fence-user",
            "fence-client",
            "missing-fence",
            "test_same_row_trigger_items",
            "insert",
            "93000000-0000-4000-8000-000000000001",
        );

        assert_eq!(
            current_fence_version(
                "test_same_row_trigger_items",
                "93000000-0000-4000-8000-000000000001",
                &mutation,
            ),
            None
        );
    }

    #[pg_test]
    fn push_fence_lookup_fails_closed_for_wrong_first_operation() {
        setup_same_row_trigger_items();
        let user_id = "fence-user";
        let client_id = "fence-client";
        let record_id = "93000000-0000-4000-8000-000000000002";
        let mutation = source_write_mutation(
            user_id,
            client_id,
            "wrong-first-fence",
            "test_same_row_trigger_items",
            "update",
            record_id,
        );
        set_source_write_mutation(&mutation.mutation_id);
        Spi::run_with_args(
            "INSERT INTO public.test_same_row_trigger_items (id, owner_id, value)
             VALUES ($1::uuid, $2, 'wrong-first')",
            &[record_id.into(), user_id.into()],
        )
        .expect("write wrong first fence");

        assert_eq!(
            current_fence_version("test_same_row_trigger_items", record_id, &mutation),
            None
        );
    }

    /// A later write in the same push unit can remove the row. The last fence then reports absence.
    #[pg_test]
    fn push_fence_lookup_reports_absence_after_later_delete() {
        setup_source_filled_items();
        let user_id = "fence-user";
        let client_id = "fence-client";
        let record_id = "93000000-0000-4000-8000-000000000003";
        let mutation = source_write_mutation(
            user_id,
            client_id,
            "later-delete-fence",
            "test_source_filled_items",
            "insert",
            record_id,
        );
        set_source_write_mutation(&mutation.mutation_id);
        Spi::run_with_args(
            "INSERT INTO public.test_source_filled_items (id, owner_id, value)
             VALUES ($1::uuid, $2, 'later-delete')",
            &[record_id.into(), user_id.into()],
        )
        .expect("write first source-filled fence");
        Spi::run_with_args(
            "DELETE FROM public.test_source_filled_items WHERE id = $1::uuid",
            &[record_id.into()],
        )
        .expect("write later delete fence");
        let delete_version = Spi::get_one_with_args::<String>(
            "SELECT row_version::text FROM synchro.sync_write_fences
             WHERE transaction_xid = pg_current_xact_id()
               AND operation = 'delete'
               AND old_record_id = $1
               AND new_record_id IS NULL",
            &[record_id.into()],
        )
        .expect("read later delete fence")
        .expect("later delete fence");

        assert_eq!(
            current_fence_version("test_source_filled_items", record_id, &mutation),
            Some(crate::push::UnitEndFence {
                version: delete_version,
                row_present: false,
            })
        );
    }
