version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      go-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: swift
    directory: /clients/swift
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      swift-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: gradle
    directory: /clients/kotlin
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      kotlin-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /clients/react-native
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      rn-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      docs-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      actions-minor-patch:
        update-types: [minor, patch]
