changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Infrastructure
      labels:
        - ci
        - infrastructure
        - dependencies
    - title: Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
