-- Independent diagnostic source schema.
-- This file never creates or mutates Synchro internal state.

CREATE TABLE cf_global_items (
    id UUID PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE cf_items (
    id UUID PRIMARY KEY,
    -- The authored corpus never authors ownership. A push materializes it
    -- from the extension's push identity context, issue #42.
    owner_id TEXT NOT NULL DEFAULT current_setting('synchro.user_id', true),
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX cf_items_owner_id_idx ON cf_items (owner_id);

-- Capture-dependency source. The extension requires one plain primary-key
-- column for the capture key and at least one captured column that the key does
-- not contain, so the authored canonical key and the captured value hold
-- separate columns.
CREATE TABLE cf_item_impacts (
    id TEXT PRIMARY KEY,
    scope_key TEXT NOT NULL
);

CREATE TABLE cf_documents (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL,
    title TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX cf_documents_owner_id_idx ON cf_documents (owner_id);

CREATE TABLE cf_document_members (
    id UUID PRIMARY KEY,
    document_id UUID NOT NULL REFERENCES cf_documents (id),
    member_id TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at TIMESTAMPTZ,
    UNIQUE (document_id, member_id)
);

CREATE INDEX cf_document_members_document_id_idx ON cf_document_members (document_id);
CREATE INDEX cf_document_members_member_id_idx ON cf_document_members (member_id);

CREATE TABLE cf_document_access (
    id UUID PRIMARY KEY,
    document_id UUID NOT NULL REFERENCES cf_documents (id),
    owner_id TEXT NOT NULL
);

CREATE INDEX cf_document_access_document_id_idx ON cf_document_access (document_id);

CREATE TABLE cf_document_notes (
    id UUID PRIMARY KEY,
    document_id UUID NOT NULL REFERENCES cf_documents (id),
    author_id TEXT NOT NULL,
    body TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX cf_document_notes_document_id_idx ON cf_document_notes (document_id);

CREATE TABLE cf_schema_queue (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL DEFAULT current_setting('synchro.user_id', true),
    authored_mutation JSONB NOT NULL,
    -- The authored registration declares default "" for this field, so the
    -- realization carries the same default.
    legacy_value TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX cf_schema_queue_owner_id_idx ON cf_schema_queue (owner_id);

CREATE TABLE cf_decode_trap (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL,
    unsupported_value POINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX cf_decode_trap_owner_id_idx ON cf_decode_trap (owner_id);

CREATE TABLE cf_late_registration (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX cf_late_registration_owner_id_idx ON cf_late_registration (owner_id);

CREATE TABLE cf_generated_items (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL,
    value TEXT NOT NULL,
    value_length INTEGER GENERATED ALWAYS AS (length(value)) STORED,
    search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', value)) STORED,
    value_upper TEXT GENERATED ALWAYS AS (upper(value)) VIRTUAL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX cf_generated_items_owner_id_idx ON cf_generated_items (owner_id);

CREATE TABLE cf_source_filled_items (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL DEFAULT current_setting('synchro.user_id', true),
    value TEXT NOT NULL,
    slug TEXT NOT NULL,
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    trigger_value TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX cf_source_filled_items_owner_id_idx ON cf_source_filled_items (owner_id);

CREATE OR REPLACE FUNCTION public.cf_source_filled_items_slug()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.slug := lower(NEW.value) || '-slug';
    RETURN NEW;
END
$$;

CREATE TRIGGER cf_source_filled_items_slug
BEFORE INSERT ON public.cf_source_filled_items
FOR EACH ROW EXECUTE FUNCTION public.cf_source_filled_items_slug();

CREATE OR REPLACE FUNCTION public.zz_cf_source_filled_items_touch()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF pg_trigger_depth() = 1 THEN
        UPDATE public.cf_source_filled_items
        SET trigger_value = NEW.value || '-triggered'
        WHERE id = NEW.id;
    END IF;
    RETURN NULL;
END
$$;

CREATE TRIGGER zz_cf_source_filled_items_touch
AFTER INSERT OR UPDATE ON public.cf_source_filled_items
FOR EACH ROW EXECUTE FUNCTION public.zz_cf_source_filled_items_touch();
