#!/usr/bin/env python3
"""Validate the closed Phase 5 release summary.

The summary is generated by the release workflow after the component gates run.
This checker derives its obligations from the authored support matrix and scenarios.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "verification"))
from packaged_smoke import SMOKE_OPERATIONS  # noqa: E402

REQUIRED_GATE_TARGETS = (
    "test-conformance",
    "test-blackbox",
    "test-adapter",
    "test-rust-core",
    "test-rust-pg",
    "test-swift-unit",
    "test-kotlin-unit",
    "test-rn-unit",
    "test-swift",
    "test-kotlin",
    "test-kotlin-instrumentation",
    "test-rn-e2e-ios",
    "test-rn-e2e-android",
    "test-packaged-consumers",
)
SHA256 = re.compile(r"^[0-9a-f]{64}$")
COMMIT = re.compile(r"^[0-9a-f]{40}$")


class SummaryError(ValueError):
    """Describe one fail-closed summary validation error."""


def load_json(path: Path, label: str) -> object:
    try:
        with path.open(encoding="utf-8") as stream:
            return json.load(stream)
    except (OSError, json.JSONDecodeError) as error:
        raise SummaryError(f"{label} is missing or malformed: {error}") from error


def required_string(value: object, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise SummaryError(f"{field} must be a nonempty string")
    return value


def expected_obligations(repo_root: Path) -> dict[str, str]:
    matrix = load_json(repo_root / "conformance/support-matrix.json", "support matrix")
    if not isinstance(matrix, dict):
        raise SummaryError("support matrix must be an object")
    cells = matrix.get("cells")
    semantic_cells = matrix.get("semantic_corpus_cell_ids")
    if not isinstance(cells, list) or not isinstance(semantic_cells, list):
        raise SummaryError("support matrix does not declare cells and semantic cells")

    cell_by_id: dict[str, dict[str, object]] = {}
    for cell in cells:
        if not isinstance(cell, dict):
            raise SummaryError("support matrix contains a malformed cell")
        cell_id = required_string(cell.get("id"), "support cell id")
        if cell_id in cell_by_id:
            raise SummaryError(f"support matrix repeats cell {cell_id}")
        cell_by_id[cell_id] = cell

    if any(not isinstance(cell_id, str) for cell_id in semantic_cells):
        raise SummaryError("support matrix contains a malformed semantic cell")
    if len(set(semantic_cells)) != len(semantic_cells):
        raise SummaryError("support matrix repeats a semantic cell")
    for cell_id in semantic_cells:
        if not isinstance(cell_id, str) or cell_id not in cell_by_id:
            raise SummaryError(f"semantic cell {cell_id!r} is not in the support matrix")

    expected: dict[str, str] = {}
    for scenario_path in sorted((repo_root / "conformance/scenarios").rglob("*.json")):
        scenario = load_json(scenario_path, f"scenario {scenario_path}")
        if not isinstance(scenario, dict):
            raise SummaryError(f"scenario {scenario_path} must be an object")
        proof_obligations = scenario.get("proof_obligations", [])
        if not isinstance(proof_obligations, list):
            raise SummaryError(f"scenario {scenario_path} has malformed proof obligations")
        for obligation in proof_obligations:
            if not isinstance(obligation, dict) or obligation.get("proof_type") != "native-e2e":
                continue
            obligation_id = required_string(obligation.get("obligation_id"), "obligation id")
            cell_id = obligation.get("support_cell_id")
            if cell_id not in semantic_cells:
                continue
            evidence_id = f"semantic/{obligation_id}"
            if evidence_id in expected:
                raise SummaryError(f"semantic obligation {evidence_id} is duplicated")
            expected[evidence_id] = "semantic"

    for cell_id, cell in cell_by_id.items():
        if cell.get("policy") == "excluded":
            continue
        for operation in SMOKE_OPERATIONS:
            expected[f"smoke/{cell_id}/{operation}"] = "smoke"

    for target in REQUIRED_GATE_TARGETS:
        expected[f"gate/{target}"] = "gate"
    return expected


def validate_hashes(value: object, label: str) -> None:
    if not isinstance(value, list) or not value:
        raise SummaryError(f"{label} must contain at least one artifact hash")
    for item in value:
        if not isinstance(item, str) or not SHA256.fullmatch(item):
            raise SummaryError(f"{label} contains an invalid artifact hash")


def validate_summary(repo_root: Path, summary_path: Path, required_kind: str | None = None) -> int:
    summary = load_json(summary_path, "phase summary")
    if not isinstance(summary, dict):
        raise SummaryError("phase summary must be an object")
    if summary.get("schema_version") != 1:
        raise SummaryError("phase summary schema_version must be 1")
    source_commit = required_string(summary.get("source_commit"), "source_commit")
    if not COMMIT.fullmatch(source_commit):
        raise SummaryError("source_commit must be a 40-character commit hash")
    try:
        head = subprocess.check_output(
            ["git", "-C", str(repo_root), "rev-parse", "--verify", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError) as error:
        raise SummaryError(f"cannot resolve the repository commit: {error}") from error
    if source_commit != head:
        raise SummaryError("phase summary source_commit does not match HEAD")

    artifact_hashes = summary.get("artifact_hashes")
    validate_hashes(artifact_hashes, "artifact_hashes")
    summary_hashes = set(artifact_hashes)
    obligations = summary.get("obligations")
    if not isinstance(obligations, list) or not obligations:
        raise SummaryError("phase summary obligations are missing or empty")

    expected = expected_obligations(repo_root)
    if required_kind is not None:
        expected = {key: kind for key, kind in expected.items() if kind == required_kind}
    actual: dict[str, dict[str, object]] = {}
    for item in obligations:
        if not isinstance(item, dict):
            raise SummaryError("phase summary contains a malformed obligation")
        obligation_id = required_string(item.get("id"), "obligation id")
        if obligation_id in actual:
            raise SummaryError(f"phase summary repeats obligation {obligation_id}")
        if obligation_id not in expected:
            raise SummaryError(f"phase summary contains unknown obligation {obligation_id}")
        if item.get("kind") != expected[obligation_id]:
            raise SummaryError(f"obligation {obligation_id} has the wrong kind")
        obligation_hashes = item.get("artifact_hashes")
        validate_hashes(obligation_hashes, f"obligation {obligation_id} artifact_hashes")
        if not set(obligation_hashes).issubset(summary_hashes):
            raise SummaryError(
                f"obligation {obligation_id} references an artifact hash outside the summary"
            )
        actual[obligation_id] = item

    missing = sorted(set(expected) - set(actual))
    if missing:
        raise SummaryError(f"phase summary is missing obligations: {', '.join(missing)}")
    for obligation_id, item in actual.items():
        if item.get("status") != "passed":
            raise SummaryError(f"obligation {obligation_id} is not passed")
        if item.get("terminal") is not True:
            raise SummaryError(f"obligation {obligation_id} is not terminal")
        test_count = item.get("test_count")
        if not isinstance(test_count, int) or isinstance(test_count, bool) or test_count <= 0:
            raise SummaryError(f"obligation {obligation_id} has zero or invalid test_count")
    if summary.get("status") != "passed":
        raise SummaryError("phase summary status is not passed")
    if summary.get("dry_run") is True:
        raise SummaryError("dry-run summary is not release evidence")
    return len(actual)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--evidence", type=Path, required=True)
    parser.add_argument("--kind", choices=("semantic", "smoke", "gate"))
    args = parser.parse_args()
    repo_root = args.repo_root.resolve()
    summary_path = args.evidence.resolve()
    try:
        count = validate_summary(repo_root, summary_path, args.kind)
    except SummaryError as error:
        print(f"phase-5-check: {error}", file=sys.stderr)
        return 1
    print(f"phase-5-check: {count} terminal obligations passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
